version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    command: gunicorn --bind 0.0.0.0:5000 autoapp:app
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  mysql_data:
