"""empty message

Revision ID: ba8100783dd9
Revises: 
Create Date: 2022-12-29 00:31:31.753666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8100783dd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_chats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('private', 'group', 'supergroup', 'channel', name='chattypesenum'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('from_user_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('edit_date', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['telegram_chats.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['telegram_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_messages')
    op.drop_table('telegram_users')
    op.drop_table('telegram_chats')
    # ### end Alembic commands ###
